apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.name }}
  labels:
    {{ .Values.webapp.labels | toYaml | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ .Values.webapp.labels | toYaml | nindent 4 }}
