imagePullSecrets: []

webapp:
  name: webapp
  labels:
    app: cnninfer
    component: webapp

  image:
    repository: islam25/webapp
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    port: 8000

  resources: 
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 1000m
      memory: 4096Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  env:
   - name: REDIS_PASSWORD
     valueFrom:
       secretKeyRef:
        name: chart-redis
        key: redis-password


inferengine:

  models:
    humanName: #name of huggingface model   (tag is the metadata.name, value is for the job for downloading and bs)
    # Delete HPA/Service 

  name: inferengine
  labels:
    app: cnninfer
    component: inferengine
    
  image:
    repository: islam25/inferengine
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  resources: 
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 1000m
      memory: 4096Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  env:
   - name: REDIS_PASSWORD
     valueFrom:
       secretKeyRef:
        name: chart-redis
        key: redis-password

