imagePullSecrets: []

webapp:
  image:
    repository: islam25/webapp
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    port: 8000

  resources: 
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 1000m
      memory: 4096Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

inferengine:
  image:
    repository: islam25/inferengine
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    port: 8000

  resources: 
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 1000m
      memory: 4096Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

